# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-02 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0024_auto_20170901_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='TutorNotification',
        ),
    ]
