# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-05 21:06
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0025_auto_20170902_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='media/tutor/'),
        ),
    ]
