# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0029_auto_20171208_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/tutor/'),
        ),
    ]
