# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-09 20:41
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0031_auto_20171209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '260x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='media/tutor/'),
        ),
    ]
