# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-01 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20170901_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
