# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-04 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20170901_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student_id',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount_due',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tutor_number',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
