# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20170904_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
