# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='other_info',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student_involved',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tutor_involved',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
