# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20170812_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student_involved',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tutor_involved',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_for_student',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_for_tutor',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
