# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_auto_20170812_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='student_id',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='notification',
            name='tutor_number',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
