# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20171208_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tutor_bank_account_name',
            field=models.CharField(default='Guaranty Trust Bank (GTB)', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tutor_bank_account_number',
            field=models.CharField(editable=False, max_length=10, verbose_name='Tutor NUBAN'),
        ),
    ]
