# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_auto_20171208_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tutor_bank_account_name',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tutor_bank_account_number',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Tutor NUBAN'),
        ),
    ]
