# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20170901_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='media/student/'),
        ),
    ]
