# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-02 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20170901_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='StudentNotification',
        ),
    ]
