# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-02 11:18
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20170902_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=image_cropping.fields.ImageCropField(upload_to=''),
        ),
    ]
