# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20170902_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='choice_color',
            field=models.CharField(default='#7c9eff', max_length=30),
        ),
    ]
