# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-15 20:40
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_student_choice_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '430x430', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=image_cropping.fields.ImageCropField(upload_to='media/tutor/'),
        ),
    ]
