# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20171015_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='choice_color',
            field=models.CharField(default='#808080', max_length=30),
        ),
    ]
