# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-15 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20171015_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='status',
            new_name='account_activation_status',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='verification',
            new_name='email_verification',
        ),
    ]
