# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-09 15:29
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_remove_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='media/student/'),
        ),
    ]
