# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20171209_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='city', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='location', max_length=63),
            preserve_default=False,
        ),
    ]
