# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-11 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20171211_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
