# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 16:16
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20171214_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '260x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=True, size_warning=True, verbose_name='cropping'),
        ),
    ]
