# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20180209_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='choice_color',
            field=models.CharField(default=b'#6598b3', max_length=30),
        ),
    ]
